FROM node:16.19.0-alpine

LABEL author=duong755

WORKDIR /react-app-dev

COPY .yarn .yarnrc.yml package.json yarn.lock ./

RUN npm i -g corepack && \
  corepack enable && \
  corepack prepare yarn@3.5.0 --activate && \
  yarn install

COPY . .

EXPOSE 3000

CMD [ "yarn", "start:swc" ]
